import { useMemo, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { BadgeCheck, ChevronDown, ImageOff, MessageCircleQuestion, Star } from 'lucide-react'

const tabs = ['Overview', 'Specifications', 'Reviews', 'Q&A']
const value = item => item == null || String(item).trim() === '' ? '' : String(item)
const stars = rating => Array.from({ length: 5 }, (_, index) => <Star key={index} size={15} fill={index < Math.round(Number(rating) || 0) ? 'currentColor' : 'none'} />)

function EmptyEvidence({ title, text }) {
  return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><h3 className="font-bold text-slate-800">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p></div>
}

export default function ProductDetailsPage({ products = [] }) {
  const { productIndex } = useParams()
  const [params, setParams] = useSearchParams()
  const initialTab = tabs.includes(params.get('tab')) ? params.get('tab') : 'Overview'
  const [tab, setTab] = useState(initialTab)
  const [openQuestion, setOpenQuestion] = useState(null)
  const product = products[Number(productIndex)]
  const specs = useMemo(() => Object.entries(product?.specs || {}).filter(([, item]) => value(item)), [product])
  const attributes = useMemo(() => Object.entries(product?.attributes || {}).filter(([, item]) => value(item?.value || item)), [product])
  const reviews = Array.isArray(product?.reviews) ? product.reviews.filter(review => value(review?.text)) : []
  const qna = Array.isArray(product?.qna) ? product.qna.filter(item => value(item?.question)) : []
  const chooseTab = next => { setTab(next); setParams(next === 'Overview' ? {} : { tab: next }) }

  if (!product) return <main className="mx-auto grid min-h-[65vh] max-w-3xl place-items-center px-5"><EmptyEvidence title="Product details are unavailable" text="Return to the comparison page and select a product result to view its source-backed details." /><Link to="/chat" className="mt-4 rounded-lg bg-[#182230] px-4 py-2 text-sm font-bold text-white">Back to comparison</Link></main>

  const detailRows = [...specs, ...attributes.filter(([key]) => !specs.some(([specKey]) => specKey.toLowerCase() === key.toLowerCase())).map(([key, item]) => [key, item?.value || item])]
  const averageReviewRating = reviews.filter(review => Number.isFinite(Number(review.rating))).length
    ? (reviews.reduce((total, review) => total + (Number(review.rating) || 0), 0) / reviews.filter(review => Number.isFinite(Number(review.rating))).length).toFixed(1)
    : null

  return <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6"><Link to="/chat" className="inline-flex items-center gap-2 text-sm font-bold text-[#68717d] hover:text-[#e8684c]">← Back to comparison</Link>
    <section className="mt-4 rounded-3xl border border-[#e5e0d7] bg-white p-5 shadow-[0_14px_40px_rgba(24,34,48,.06)] sm:p-8"><div className="grid gap-7 md:grid-cols-[minmax(220px,.7fr)_minmax(0,1.3fr)]"><div className="grid min-h-64 place-items-center overflow-hidden rounded-2xl bg-slate-100">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} className="h-full max-h-80 w-full object-contain" onError={event => { event.currentTarget.style.display = 'none' }} /> : <ImageOff className="text-slate-400" size={42} />}</div><div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#e8684c]">Product details</p><h1 className="mt-2 text-2xl font-black leading-tight text-[#182230] sm:text-3xl">{product.name}</h1></div>{product.recommended && <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Top pick</span>}</div><p className="mt-5 text-3xl font-black text-indigo-700">{product.price || 'Price unavailable'}</p><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm">{product.rating != null && <span className="inline-flex items-center gap-1 font-bold text-amber-600"><Star size={17} fill="currentColor" />{product.rating} / 5</span>}{product.rating_count != null && <span className="text-slate-500">{Number(product.rating_count).toLocaleString('en-IN')} ratings</span>}{product.link ? <a href={product.link} target="_blank" rel="noopener noreferrer" className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600 hover:text-indigo-700">{product.source || 'Source unavailable'}</a> : <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{product.source || 'Source unavailable'}</span>}</div>{product.delivery && <p className="mt-3 text-sm font-medium text-emerald-700">Delivery: {product.delivery}</p>}{product.verified && <p className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-emerald-700"><BadgeCheck size={15} />Verified listing</p>}</div></div>
      <div className="mt-8 flex gap-1 overflow-x-auto border-b border-slate-200" role="tablist">{tabs.map(item => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => chooseTab(item)} className={`shrink-0 border-b-2 px-4 py-3 text-sm font-bold ${tab === item ? 'border-[#e8684c] text-[#182230]' : 'border-transparent text-slate-500 hover:text-slate-800'}`}>{item}{item === 'Reviews' && reviews.length ? ` (${reviews.length})` : ''}{item === 'Q&A' && qna.length ? ` (${qna.length})` : ''}</button>)}</div>
      <div className="pt-6">{tab === 'Overview' && <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div><h2 className="text-lg font-black text-[#182230]">Overview</h2>{product.description ? <p className="mt-3 whitespace-pre-line leading-7 text-slate-600">{product.description}</p> : <p className="mt-3 text-sm text-slate-500">A detailed description was not available from this listing.</p>}</div><dl className="grid content-start gap-3 rounded-2xl bg-slate-50 p-5 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Retailer</dt><dd className="text-right font-bold text-slate-800">{product.source || 'Not available'}</dd></div>{product.brand && product.brand !== 'Unknown' && <div className="flex justify-between gap-4"><dt className="text-slate-500">Brand</dt><dd className="text-right font-bold text-slate-800">{product.brand}</dd></div>}{product.category && <div className="flex justify-between gap-4"><dt className="text-slate-500">Category</dt><dd className="text-right font-bold text-slate-800">{product.category}</dd></div>}{product.offers && <div className="flex justify-between gap-4"><dt className="text-slate-500">Offers</dt><dd className="text-right font-bold text-slate-800">{product.offers}</dd></div>}</dl></div>}
      {tab === 'Specifications' && (detailRows.length ? <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-bold">Specification</th><th className="px-5 py-3 font-bold">Value</th></tr></thead><tbody>{detailRows.map(([key, item]) => <tr key={key} className="border-t border-slate-100"><th className="w-1/3 px-5 py-4 font-semibold text-slate-600">{key}</th><td className="px-5 py-4 text-slate-800">{String(item)}</td></tr>)}</tbody></table></div> : <EmptyEvidence title="No specifications available" text="This listing did not return structured specifications." />)}
      {tab === 'Reviews' && (reviews.length ? <div><div className="mb-5 flex flex-wrap items-center gap-4 rounded-2xl bg-amber-50 p-5"><div><p className="text-xs font-bold uppercase tracking-wide text-amber-800">Customer reviews</p><p className="mt-1 flex items-center gap-1 text-2xl font-black text-slate-800"><Star size={21} fill="currentColor" className="text-amber-500" />{averageReviewRating || product.rating || 'Not rated'}</p></div><p className="text-sm text-slate-600">{reviews.length} scraped review{reviews.length === 1 ? '' : 's'} available</p></div><div className="space-y-3">{reviews.map((review, index) => <article key={`${review.text}-${index}`} className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-wrap items-center gap-3 text-sm">{review.rating != null && <span className="flex text-amber-500">{stars(review.rating)}</span>}{review.author && <strong className="text-slate-800">{review.author}</strong>}{review.verified_purchase && <span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">Verified purchase</span>}</div><p className="mt-3 leading-7 text-slate-700">{review.text}</p>{review.source && <p className="mt-3 text-xs font-semibold text-slate-500">Source: {review.source}</p>}</article>)}</div></div> : <EmptyEvidence title="No scraped reviews available" text={product.deep_scraped ? 'The retailer did not return usable review text for this listing.' : 'Run a deep comparison from Analytics to collect retailer reviews when available.'} />)}
      {tab === 'Q&A' && (qna.length ? <div className="space-y-3">{qna.map((item, index) => <article key={`${item.question}-${index}`} className="rounded-2xl border border-slate-200"><button type="button" onClick={() => setOpenQuestion(openQuestion === index ? null : index)} className="flex w-full items-center justify-between gap-4 p-5 text-left"><span className="flex items-start gap-3 font-bold text-slate-800"><MessageCircleQuestion className="mt-0.5 shrink-0 text-[#e8684c]" size={18} />{item.question}</span><ChevronDown className={`shrink-0 text-slate-500 transition ${openQuestion === index ? 'rotate-180' : ''}`} /></button>{openQuestion === index && <div className="border-t border-slate-100 px-5 pb-5 pt-4"><p className="leading-7 text-slate-700">{item.answer || 'An answer was not available from the retailer.'}</p>{item.source && <p className="mt-3 text-xs font-semibold text-slate-500">Source: {item.source}</p>}</div>}</article>)}</div> : <EmptyEvidence title="No customer questions available" text={product.deep_scraped ? 'The retailer did not return usable questions and answers for this listing.' : 'Run a deep comparison from Analytics to collect Q&A when available.'} />)}</div>
    </section></main>
}
